rendezvous_server = '172.232.211.116:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = '00bmcqKjkjq9VjPpIKIiY4n2nn'

[options]
relay-server = '172.232.211.116'
temporary-password-length = '6'
enable-lan-discovery = 'N'
custom-rendezvous-server = '172.232.211.116'
key = 'FGnqzqGE19xjRrIkoWCoLTOfKJtKh06dLYRmnzOjJRs='
verification-method = 'use-permanent-password'
auto-disconnect-timeout = '5'
allow-auto-disconnect = 'Y'
allow-auto-update = 'Y'
direct-server = 'Y'
av1-test = 'Y'
access-mode = 'full'

