rendezvous_server = '172.232.211.116:21116'
nat_type = 2
serial = 0
unlock_pin = ''
trusted_devices = '00AYbxJbKoCI7UB+nG2ImSLHbZXf5cPULKG08tr5Y0FeoTieNqO9Z2n9Exew=='

[options]
av1-test = 'Y'
custom-rendezvous-server = '172.232.211.116'
auto-disconnect-timeout = '5'
allow-remote-config-modification = 'Y'
relay-server = '172.232.211.116'
allow-auto-update = 'Y'
enable-lan-discovery = 'N'
allow-remove-wallpaper = 'Y'
access-mode = 'full'
key = 'FGnqzqGE19xjRrIkoWCoLTOfKJtKh06dLYRmnzOjJRs='
